# docker-compose up -d --build
version: '2.4'
services:
  letsencrypt:
    image: linuxserver/letsencrypt:latest
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=admin@vathes.com
      - URL=datajoint.io # for testdev deploy
      - SUBDOMAINS=testdev # for testdev deploy
      # - URL=internationalbrainlab.org # for client deploy
      # - SUBDOMAINS=djcompute # for client deploy
      - TZ=Europe/London
      - ONLY_SUBDOMAINS=true
      - STAGING=true # UNcomment for testdev
    ports:
      - "80:80"
      - "443:443"
    # cap_add:
    #   - NET_ADMIN
    volumes:
      - ./letsencrypt-keys:/etc/letsencrypt/live
    networks:
      - main   
networks:
    main:
        ipam:
            driver: default
            config:
                - subnet: 10.28.0.0/16
