version: '3'
services:
  iblapi:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/src/iblapi
    ports:
      - "5000:5000"
    entrypoint: ["/src/iblapi/run-ibl-api.prod.sh"]
    # entrypoint: ["/src/iblapi/run-ibl-api.dev.sh", "development"]
  iblapi-dj:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend/notebooks:/notebooks
      - ./backend:/src/iblapi
    ports:
      - "8888:8888"
    links:
      - iblapi
  ibl-navigator:
    build: .
    env_file: .env
    volumes:
      - .:/src/ibl-navigator
    ports:
      - "4200:4200"
