# docker-compose up -d --build
version: '2.4'
x-net: &net
  networks:
      - main
services:
  iblapi:
    extends:
      file: ./docker-compose-build.yml
      service: iblapi
    image: iblapi:v1.0
    #entrypoint: ["/src/iblapi/run-ibl-api.dev.sh", "development"]
    <<: *net
  ibl-navigator:
    extends:
      file: ./docker-compose-build.yml
      service: ibl-navigator
    build: 
      context: ./ibl-frontend
      dockerfile: Dockerfile.dev
    image: ibl-navigator:v1.0
    volumes:
      - ./ibl-frontend/frontend-content/src:/frontend/src
      - ./ibl-frontend/frontend-content/angular.json:/frontend/angular.json
    <<: *net
  ibl-node-server:
    extends:
      file: ./docker-compose-build.yml
      service: ibl-node-server
    image: ibl-node-server:v1.0
    # command: nodemon /src/server.js
    volumes:
      - ./node_server/app.js:/src/app.js
    <<: *net
  nginx:
    extends:
      file: ./docker-compose-build.yml
      service: nginx
    ports:
    - "3333:3333" # node-server
    - "5000:5000" # iblapi
    - "9000:9000" # frontend
    <<: *net
networks:
    main:
        ipam:
            driver: default
            config:
                - subnet: 10.28.0.0/16
