# docker-compose up -d --build
version: '2.4'
x-net: &net
  networks:
      - main
services:
  iblapi:
    <<: *net
    # build: ./backend
    image: registry.vathes.com/ibl-navigator/iblapi:v0.13 # for client deploy
    # image: registry.vathes.com/ibl-navigator/iblapi:v0.2-dev14 # add -dev ending to testdev tag
    # image: registry.vathes.com/ibl-navigator/iblapi:v0.0-public3 # for public demo
    environment:
    - DJ_USER=maho
    # - DJ_USER=ibl-navigator # for public demo
    - DJ_HOST=datajoint.internationalbrainlab.org
    # - DJ_HOST=datajoint-public.internationalbrainlab.org # for public demo
    - AWS_DEFAULT_REGION=us-east-1
    - WORKER_COUNT=4
    env_file: ./.env
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:5000/v0/lab > /dev/null 2>&1 || exit 1
      timeout: 3s
      retries: 20
    # volumes:
    #   - ./backend:/src/iblapi
    # ports:
    #   - "5000:5000"
    entrypoint: ["/src/iblapi/run-ibl-api.prod.sh"]
    # entrypoint: ["/src/iblapi/run-ibl-api.dev.sh", "development"]
    # cpus: 0.65
    #cpu_quota: 100000
    #cpu_period: 100ms
  ibl-navigator:
    <<: *net
    # build: ./ibl-frontend
    image: registry.vathes.com/ibl-navigator/frontend:v0.16 # for client deploy
    # image: registry.vathes.com/ibl-navigator/frontend:v0.2-dev18 # add -dev ending to testdev tag
    # image: registry.vathes.com/ibl-navigator/frontend:v0.0-public8 # for public demo
    # environment:
    # - PROD_NODE_BACKEND=https://testdev.datajoint.io/api # for testdev deploy
    # - PROD_NODE_BACKEND=https://fakeservices.datajoint.io/api # for client deploy
    # - PROD_NODE_BACKEND=https://djcompute.internationalbrainlab.org/api # for client deploy
    # - PROD_NODE_BACKEND=https://data.internationalbrainlab.org/api # for public demo deploy
    # - PROD_NODE_BACKEND=http://localhost:3333
    # - DEV_NODE_API=http://localhost:9000/api
    # - DEV_NODE_BACKEND=http://localhost:9000
    healthcheck:
      test: curl --fail http://localhost:9000 || exit 1
      timeout: 3s
      retries: 20
    # ports:
    #   - "9000:9000"
  ibl-node-server:
    <<: *net
    # build: ./node_server
    image: registry.vathes.com/ibl-navigator/node-server:v0.8 # for client deploy
    # image: registry.vathes.com/ibl-navigator/node-server:v0.2-dev6 # add -dev ending to testdev tag
    # image: registry.vathes.com/ibl-navigator/node-server:v0.0-public3 # for public demo
    environment:
    - NODE_ENV=development
    - DEMO_USERNAME=ibluser
    - PY_BACKEND=http://iblapi:5000
    env_file: .env
    healthcheck:
      test: curl --fail http://localhost:3333/version || exit 1
      timeout: 3s
      retries: 20
      # interval: 1s
    # volumes:
    #   - ./node_server:/src
    # ports:
    #   - "3333:3333"
  letsencrypt:
    <<: *net
    image: linuxserver/letsencrypt:amd64-0.38.0-ls62
    # image: linuxserver/letsencrypt:amd64-0.38.0-ls62 # from publicdemo
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=service-health@vathes.com
      # - URL=datajoint.io # for testdev deploy
      # - URL=internationalbrainlab.org # for client or public demo deploy
      # # - SUBDOMAINS=testdev # for testdev deploy
      # - SUBDOMAINS=djcompute # for client deploy
      # - SUBDOMAINS=data # for public demo deploy
      - TZ=Europe/London
      - ONLY_SUBDOMAINS=true
      - STAGING=true # UNcomment for testdev
      - VALIDATION=http
    healthcheck:
      # test: ["CMD-SHELL","if","[", "$$(expr", "$$(date", "+%s)","-","$$(stat","-c","%Y","$$(ls","-la","/config/etc/letsencrypt/live/*.*/fullchain.pem","|","awk","'{print","sprintf(\"%s/%s\",\"/config/etc/letsencrypt/live/*.*\",$$11)}')))","-lt","\"7776000\"","];","then","exit","0;else","exit","1;fi"]
      # test: if [ $$(expr $(date +%s) - $$(stat -c %Y $(ls -la /config/etc/letsencrypt/live/*.*/fullchain.pem | awk '{print sprintf("%s/%s", "/config/etc/letsencrypt/live/*.*", $11)}'))) -lt "7776000" ]; then exit 0;else exit 1;fi
      test: /healthcheck.sh
      timeout: 5s
      retries: 300
      interval: 1s
    # ports:
    #   - "80:80"
    #   - "443:443"
    # cap_add:
    #   - NET_ADMIN
    # volumes:
    #   - ./letsencrypt-keys:/config/etc/letsencrypt
    #   - ./letsencrypt/healthcheck.sh:/healthcheck.sh
    # depends_on:
    #   nginx:
    #     condition: service_healthy
  nginx:
    <<: *net
    image: raphaelguzman/nginx:v0.0.7
    environment:
      - ADD_frontend_TYPE=REST
      - ADD_frontend_ENDPOINT=ibl-navigator:9000
      - ADD_frontend_PREFIX=/
      - ADD_nodebackend_TYPE=REST
      - ADD_nodebackend_ENDPOINT=ibl-node-server:3333
      - ADD_nodebackend_PREFIX=/api
      - HTTPS_PASSTHRU=TRUE
      # - SUBDOMAINS=djcompute
      # - URL=internationalbrainlab.org
      - CERTBOT_HOST=letsencrypt:80
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./letsencrypt-keys:/etc/letsencrypt:ro
    # depends_on:
    #   iblapi:
    #     condition: service_healthy
    #   ibl-node-server:
    #     condition: service_healthy
    #   ibl-navigator:
    #     condition: service_healthy
networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 10.28.0.0/16
